[config]
schemaVersion = "0.0.1"

[package]
namespace = "KaitoMajima"
name = "PromisedEigong"
versionNumber = "1.1.2"
description = "A retelling of Eigong's fight at the height of her determination and abilities in her quest to reach immortality."
websiteUrl = "https://github.com/KaitoMajima/PromisedEigongMod"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
